name: Compile PDFs

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile
      run: make

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: pdflatex build
        branch: pdflatex_build
        title: '[CI] pdflatex build'
